name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 12 * * 0'

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.24.x', '1.25.x']
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}

    - name: gofmt check
      run: diff <(gofmt -d .) <(echo -n "")

    - name: Test
      run: go test -v ./...
